version: '3'

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

    networks:
        - nginx-proxy

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
